name: test backend

on:
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # deno: ["v1.x", "nightly"]
        deno: ["v1.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno --version
      - run: npm run test:backend
        env:
          APP_AWS_ACCESS_KEY_ID: ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
          APP_AWS_SECRET_ACCESS_KEY: ${{secrets.APP_AWS_SECRET_ACCESS_KEY}}
          APP_ENV: live